definitions:
  models.ErrorResponse:
    properties:
      code:
        description: Machine-friendly error message for handling in front-end
        example: lowercase_and_underscores
        type: string
      message:
        description: Human-friendly error message for the user
        example: Capitalization and spaces
        type: string
    type: object
  models.Serie:
    properties:
      id:
        description: Unique identifier for the series
        example: 10
        type: integer
      lastEpisodeWatched:
        description: Last episode watched of the series
        example: 15
        type: integer
      ranking:
        description: Score of the series used for ranking
        example: 10
        type: integer
      status:
        description: Current status of the series; "Watching", "Plan to Watch", "Dropped",
          "Completed"
        example: Watching
        type: string
      title:
        description: Title of the series
        example: Breaking Bad
        type: string
      totalEpisodes:
        description: Quantity of episodes in the series
        example: 24
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/series:
    get:
      consumes:
      - application/json
      description: Get a list of all series in the database
      produces:
      - application/json
      responses:
        "200":
          description: Success, array of all fetched series
          schema:
            items:
              $ref: '#/definitions/models.Serie'
            type: array
        "500":
          description: Internal Server Error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Retrieve all series
      tags:
      - series
    post:
      consumes:
      - application/json
      description: Inserts a new series into the database, make sure the series object
        includes all the necessary fields.
      parameters:
      - description: Series info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Serie'
      produces:
      - application/json
      responses:
        "201":
          description: Created, newly created series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. invalid input fields
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Series conflict, eg. negative ranking or duplicate title
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new series
      tags:
      - series
  /api/series/{id}:
    delete:
      consumes:
      - application/json
      description: Inserts a new series into the database, make sure the series object
        includes all the necessary fields.
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid input, eg. non-integer ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. ID that doesn't exist in the databas
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, eg. database error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Remove an existing series from the database
      tags:
      - series
    get:
      consumes:
      - application/json
      description: Get details of a series using the provided ID
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success, fetched series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. non-integer ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. an ID that doesn't exist in the database
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Retrieve a series by ID
      tags:
      - series
    put:
      consumes:
      - application/json
      description: Updates details of an existing series
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success, updated series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. non-integer ID or invalid input fields
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. ID that doesn't exist in the database
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Series conflict, eg. invalid values for episode or negative
            ranking
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update an existing series
      tags:
      - series
  /api/series/{id}/downvote:
    patch:
      consumes:
      - application/json
      description: Decreases the rating (score) of the series with the specified ID
        by one vote.
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success, updated series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. non-integer ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. ID that doesn't exist in the database
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Series conflict, eg. downvoting past 0
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Decrease series score
      tags:
      - series
  /api/series/{id}/episode:
    patch:
      consumes:
      - application/json
      description: Increments the current episode number of a series by one
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success, updated series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. non-integer ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. ID that doesn't exist in the database
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Series conflict, eg. trying to increment episode past last
            one
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Advance series episode count
      tags:
      - series
  /api/series/{id}/status:
    patch:
      consumes:
      - application/json
      description: Updates the status of the series with the specified ID.
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success, updated series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. non-integer ID or invalid status
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. ID that doesn't exist in the database
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update series status
      tags:
      - series
  /api/series/{id}/upvote:
    patch:
      consumes:
      - application/json
      description: Increases the rating (score) of the series with the specified ID
        by one vote.
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success, updated series
          schema:
            $ref: '#/definitions/models.Serie'
        "400":
          description: Invalid input, eg. non-integer ID
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Series not found, eg. ID that doesn't exist in the database
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error, unspecified internal errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Increase series score
      tags:
      - series
swagger: "2.0"
